### PR TITLE
Changed some commands to allow windows compatibility

### PR DESCRIPTION
**Pull request by jbornemann**

### CODE REVIEW

**Comment by jbornemann** [comment]
@gavioto ill merge this back if we get some reasoning about which environment one is operating in

**Comment by gavioto** [comment]
I think this merge request can be canceled now. I'm not sure that the solution works well in windows including this change. 

I tried to use this plugin in windows but the plugin doesn't detect the git repository.

**Comment by jbornemann** [comment]
The $null will only work in powershell fwiw

**Comment by gavioto** [comment]
I tested, and the changes works in Windows. 
The problem was that 2> /dev/nulll doesn't work in Power Shell and which is not a native Windows command (you can see Vagrant source why they use which and where depending of the O.S.)

image

For vagrant-git-sync to support Windows I think only this two changes should be done, but it requires to work also in linux, so any kind of selection depending of the O.S. should be done in some part of the code. I'm not a Ruby developer, do you think you can integrate the changes including O.S. detection? (I think vagrant and linux may have a method for this. 

Alternativaly, I found this on stackoverlow https://stackoverflow.com/questions/26811089/vagrant-how-to-have-host-platform-specific-provisioning-steps

**Pull request closed without merging**
