### PR TITLE
Added Windows compatibility with some reasoning

### PR DESCRIPTION
**Pull request by gavioto**
I added support for windows with explicit O.S. detection.

Uses Vagrant utils to detect operating system. 

The changes only takes into account the windows exception rule and mantains the backward compatibility using original code in other case.

### CODE REVIEW

**Comment by jbornemann** [comment]
Great! Thanks!

**Comment by gavioto** [comment]
Thanks! When do you think the new version will be available?

**Comment by jbornemann** [comment]
I published it!

**Comment by gavioto** [comment]
Thank you. I didn't see any changes in the repo about 1.0.3.

**Pull request merged**
